name = input('Enter a name: ')
ad1 = input('Enter an adjective: ')
ad2 = input('Enter an adjective: ')
adv = input('Enter an adverb: ')
food1 = input('Enter a food: ')
food2 = input('Enter another food: ')
noun = input('Enter a noun: ')
place = input('Enter a place: ')
verb = input('Enter a verb: ')
print('\n\n\n\n\n\n\n\n\n\n\n'+name+' was planning a dream vacation to '+place+'.\n'+name+' was especially looking forward to trying the local\ncuisine, including '+ad1+' '+food1+' and '+food2+'.\n\n'+name+' will have to practice the language '+adv+' to make it easier to '+verb+' with people.\n\n'+name+' has a long list of sights to see, including the '+noun+' museum and the '+ad2+' park.')
